/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gang_fictalk_jni_NativeMethods */

#ifndef _Included_com_gang_fictalk_jni_NativeMethods
#define _Included_com_gang_fictalk_jni_NativeMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    InitJniEnv
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gang_fictalk_jni_NativeMethods_InitJniEnv
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    IsListenRun
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_gang_fictalk_jni_NativeMethods_IsListenRun
  (JNIEnv *, jclass);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    SetLanguage
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_gang_fictalk_jni_NativeMethods_SetLanguage
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    Login
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_Login
  (JNIEnv *, jclass, jstring, jstring, jstring, jint, jboolean);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    Logout
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_Logout
  (JNIEnv *, jclass);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    Relogin
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_Relogin
  (JNIEnv *, jclass);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    ToReConnect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gang_fictalk_jni_NativeMethods_ToReConnect
  (JNIEnv *, jclass);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    Register
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_Register
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    SearchUsers
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_SearchUsers
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    UpdateUserInfo
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_UpdateUserInfo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    AddFriend
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_AddFriend
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    AccpetFriend
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_AccpetFriend
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    RemoveFriend
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_RemoveFriend
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    GetFriends
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_GetFriends
  (JNIEnv *, jclass);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    GetUserLocal
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_GetUserLocal
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    GetUserInfo
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_GetUserInfo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    NewFriends
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_NewFriends
  (JNIEnv *, jclass);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    DeleteNewFriend
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_gang_fictalk_jni_NativeMethods_DeleteNewFriend
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    GetNearbyPeople
 * Signature: (FFI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_GetNearbyPeople
  (JNIEnv *, jclass, jfloat, jfloat, jint);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    ClearLocation
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_ClearLocation
  (JNIEnv *, jclass);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    ChangeMark
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_ChangeMark
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    ChangeHead
 * Signature: ([BI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_ChangeHead
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    ChangeNick
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_ChangeNick
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    ChangeSex
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_ChangeSex
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    ChangePhone
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_ChangePhone
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    ChangeQQ
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_ChangeQQ
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    ChangeEmail
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_ChangeEmail
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    QueryWallet
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_QueryWallet
  (JNIEnv *, jclass);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    ChangeUserCircleBackImg
 * Signature: ([BI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_ChangeUserCircleBackImg
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    AddPushInfo
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_AddPushInfo
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    PayMoney
 * Signature: (IFLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_PayMoney
  (JNIEnv *, jclass, jint, jfloat, jstring);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    ClearCache
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_gang_fictalk_jni_NativeMethods_ClearCache
  (JNIEnv *, jclass);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    GetChatList
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_GetChatList
  (JNIEnv *, jclass);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    GetChatMsg
 * Signature: (JZII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_GetChatMsg
  (JNIEnv *, jclass, jlong, jboolean, jint, jint);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    GetChatMsgLast
 * Signature: (JZJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_GetChatMsgLast
  (JNIEnv *, jclass, jlong, jboolean, jlong);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    DeleteChatList
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_gang_fictalk_jni_NativeMethods_DeleteChatList
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    ChatSetTop
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_gang_fictalk_jni_NativeMethods_ChatSetTop
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    SendMsg
 * Signature: (JLjava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_SendMsg
  (JNIEnv *, jclass, jlong, jstring, jboolean);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    SendImageMsg
 * Signature: (JZ[BI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_SendImageMsg
  (JNIEnv *, jclass, jlong, jboolean, jbyteArray, jint);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    SetReaded
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_com_gang_fictalk_jni_NativeMethods_SetReaded
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    SetReaded2
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_gang_fictalk_jni_NativeMethods_SetReaded2
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    SendRedbag
 * Signature: (Ljava/lang/String;Ljava/lang/String;FJIIZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_SendRedbag
  (JNIEnv *, jclass, jstring, jstring, jfloat, jlong, jint, jint, jboolean);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    RobRedbag
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_RobRedbag
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    GetRedbag
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_GetRedbag
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    GetRedbagDetail
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_GetRedbagDetail
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    SendAdBag
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[BIFI[BI[BI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_SendAdBag
  (JNIEnv *, jclass, jstring, jstring, jstring, jbyteArray, jint, jfloat, jint, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    SendRedbagToActive
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_SendRedbagToActive
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    GetRedBagSend
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_GetRedBagSend
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    GetRedBagRecv
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_GetRedBagRecv
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    CreateGroup
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_CreateGroup
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    GetGroups
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_GetGroups
  (JNIEnv *, jclass);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    GetGroupInfoAndMember
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_GetGroupInfoAndMember
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    GetGroupInfoLocal
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_GetGroupInfoLocal
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    GetGroupMember
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_GetGroupMember
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    RenameGroup
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_RenameGroup
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    GroupInvite
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_GroupInvite
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    GroupRemove
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_GroupRemove
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    GroupMute
 * Signature: (JZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_GroupMute
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    GroupExit
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_GroupExit
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    SendCircle
 * Signature: (Ljava/lang/String;[Ljava/lang/Object;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_SendCircle
  (JNIEnv *, jclass, jstring, jobjectArray, jint);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    GetCircleLastUpdateUser
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_gang_fictalk_jni_NativeMethods_GetCircleLastUpdateUser
  (JNIEnv *, jclass);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    GetCircleList
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_GetCircleList
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    GetCircleListByUser
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_GetCircleListByUser
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    GetCircleComment
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_GetCircleComment
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    CommentCircle
 * Signature: (JLjava/lang/String;JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_CommentCircle
  (JNIEnv *, jclass, jlong, jstring, jlong, jint);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    RemoveCircle
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_RemoveCircle
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    RemoveCircleComment
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_RemoveCircleComment
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    GetMyGift
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_GetMyGift
  (JNIEnv *, jclass);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    GetStoreGift
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_GetStoreGift
  (JNIEnv *, jclass);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    BuyGift
 * Signature: (JIFLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_BuyGift
  (JNIEnv *, jclass, jlong, jint, jfloat, jstring);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    SendGift
 * Signature: (JJILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_SendGift
  (JNIEnv *, jclass, jlong, jlong, jint, jstring);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    AcceptGift
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_AcceptGift
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    GetGiftInfo
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_GetGiftInfo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    GetRes
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_GetRes
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    GetPhoneCards
 * Signature: (III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_GetPhoneCards
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_gang_fictalk_jni_NativeMethods
 * Method:    SetPhoneCardUsed
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gang_fictalk_jni_NativeMethods_SetPhoneCardUsed
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
